# Generated by Django 4.0.4 on 2022-05-03 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='word',
            name='word_translation',
            field=models.CharField(default='DEFAULT VALUE', max_length=200),
        ),
        migrations.DeleteModel(
            name='Translation',
        ),
        migrations.AddField(
            model_name='choice',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.word'),
        ),
    ]
