# Generated by Django 4.0.4 on 2022-05-04 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_choice_word_word_translation_delete_translation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
