# Generated by Django 4.0.4 on 2022-05-04 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_language_remove_word_pub_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='word',
        ),
    ]
